import { GuildWarBoard, GuildMember, GuildWarSession } from '../types';

export const DEFAULT_GUILD_SESSIONS: GuildWarSession[] = [
  { id: 's1', label: 'Tuần 1/T1' },
  { id: 's2', label: 'Tuần 1/T2' },
  { id: 's3', label: 'Tuần 2' },
  { id: 's4', label: 'Tuần 3/T1' },
  { id: 's5', label: 'Tuần 3/T2' },
  { id: 's6', label: 'Tuần 4' },
];

export const INITIAL_GUILD_MEMBERS: Omit<GuildMember, 'id'>[] = [
  {
    stt: 1,
    ingame: 'Cửu U Vương',
    className: 'Cửu Linh',
    guildRole: 'Trưởng Lão',
    participation: 'Cả hai',
    discord: 'cuuuvuong#0001',
    team: 'Mid',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 2,
    ingame: 'Vy Lì',
    className: 'Cửu Linh',
    guildRole: 'Đường Chủ',
    participation: 'Bang chiến',
    discord: 'vyli#1234',
    team: 'Mid',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 3,
    ingame: 'Ninh Rain',
    className: 'Cửu Linh',
    guildRole: 'Tinh Anh',
    participation: 'Cả hai',
    discord: 'ninhrain#9999',
    team: 'Mid',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 4,
    ingame: 'Apple Snow',
    className: 'Cửu Linh',
    guildRole: 'Thành Viên',
    participation: 'Cả hai',
    discord: 'applesnow#2026',
    team: 'Mid',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 5,
    ingame: 'Rannn',
    className: 'Huyết Hà',
    guildRole: 'Bang Chủ',
    participation: 'Cả hai',
    discord: 'rannn#7777',
    team: 'Cơ động',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 6,
    ingame: 'Dâm Dâm Công Tử',
    className: 'Huyết Hà',
    guildRole: 'Đường Chủ',
    participation: 'Bang chiến',
    discord: 'damdam#6666',
    team: 'Cơ động',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 7,
    ingame: 'ViVy',
    className: 'Long Ngâm',
    guildRole: 'Phó Bang',
    participation: 'Cả hai',
    discord: 'vivy#8888',
    team: 'Đẩy trụ',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 8,
    ingame: 'Cừu Béo',
    className: 'Long Ngâm',
    guildRole: 'Tinh Anh',
    participation: 'Cả hai',
    discord: 'cuubeo#3333',
    team: 'Đẩy trụ',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 9,
    ingame: 'Libra',
    className: 'Thần Tương',
    guildRole: 'Trưởng Lão',
    participation: 'Cả hai',
    discord: 'libra#1111',
    team: 'Mid',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 10,
    ingame: 'Yên Nguyệt Cửu',
    className: 'Thần Tương',
    guildRole: 'Đường Chủ',
    participation: 'Bang chiến',
    discord: 'yennguyetcuu#4444',
    team: 'Mid',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 11,
    ingame: 'Xiao Yu',
    className: 'Thần Tương',
    guildRole: 'Thành Viên',
    participation: 'Raid',
    discord: 'xiaoyu#5555',
    team: 'Mid',
    attendance: { s1: false, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 12,
    ingame: 'Khưu Vĩ Khanh',
    className: 'Thiết Y',
    guildRole: 'Trưởng Lão',
    participation: 'Cả hai',
    discord: 'khuuvikhanh#1010',
    team: 'Đẩy trụ',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 13,
    ingame: 'AKMA',
    className: 'Thiết Y',
    guildRole: 'Thành Viên',
    participation: 'Bang chiến',
    discord: 'akma#2020',
    team: 'Đẩy trụ',
    attendance: { s1: false, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 14,
    ingame: 'Thần Cẩn',
    className: 'Thiết Y',
    guildRole: 'Đường Chủ',
    participation: 'Cả hai',
    discord: 'thancan#3030',
    team: 'Đẩy trụ',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 15,
    ingame: 'Tiêu Niên',
    className: 'Toái Mộng',
    guildRole: 'Tinh Anh',
    participation: 'Cả hai',
    discord: 'tieunien#4040',
    team: 'Cơ động',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 16,
    ingame: 'Loi Nhoi',
    className: 'Toái Mộng',
    guildRole: 'Thành Viên',
    participation: 'Bang chiến',
    discord: 'loinhoi#5050',
    team: 'Cơ động',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 17,
    ingame: 'RAINY',
    className: 'Long Ngâm',
    guildRole: 'Thành Viên',
    participation: 'Cả hai',
    discord: 'rainy#6060',
    team: 'Cơ động',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 18,
    ingame: 'Chiiyaki',
    className: 'Tố Vấn',
    guildRole: 'Đường Chủ',
    participation: 'Cả hai',
    discord: 'chiiyaki#7070',
    team: 'Mid',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 19,
    ingame: 'Lục Phượng Yen',
    className: 'Tố Vấn',
    guildRole: 'Thành Viên',
    participation: 'Cả hai',
    discord: 'lucphuongyen#8080',
    team: 'Đẩy trụ',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 20,
    ingame: 'Shen',
    className: 'Tố Vấn',
    guildRole: 'Tinh Anh',
    participation: 'Cả hai',
    discord: 'shen#9090',
    team: 'Cơ động',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 21,
    ingame: 'Tiến Mỹ',
    className: 'Tố Vấn',
    guildRole: 'Thành Viên',
    participation: 'Bang chiến',
    discord: 'tienmy#1122',
    team: 'Mid',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
  {
    stt: 22,
    ingame: 'Hồ Uyển Ly',
    className: 'Tố Vấn',
    guildRole: 'Phó Bang',
    participation: 'Cả hai',
    discord: 'houyenly#3344',
    team: 'Đẩy trụ',
    attendance: { s1: true, s2: true, s3: true, s4: true, s5: true, s6: false },
  },
];

export function createSampleGuildWarBoard(boardNumber: number = 1): GuildWarBoard {
  const timestamp = Date.now();
  return {
    id: `gw_board_${timestamp}_${Math.random().toString(36).substring(2, 7)}`,
    title: `BANG CHIẾN TUẦN ${boardNumber}`,
    scheduleTime: 'T7 20:00 & CN 20:00',
    targetName: 'Chiếm Lãnh Địa / Đẩy Trụ',
    sessions: DEFAULT_GUILD_SESSIONS.map((s) => ({ ...s })),
    members: INITIAL_GUILD_MEMBERS.map((m, idx) => ({
      ...m,
      id: `gw_m_${timestamp}_${idx + 1}`,
      stt: idx + 1,
    })),
    minAttendanceRequired: 4,
    reportDate: '30/08/2026',
    createdAt: timestamp,
  };
}

export function createEmptyGuildWarBoard(
  boardNumber: number = 1,
  title?: string,
  scheduleTime: string = 'T7 20:00 & CN 20:00',
  targetName: string = 'Công Thành / Đẩy Trụ'
): GuildWarBoard {
  const timestamp = Date.now();
  return {
    id: `gw_board_${timestamp}_${Math.random().toString(36).substring(2, 7)}`,
    title: title?.trim() || `BANG CHIẾN TUẦN ${boardNumber}`,
    scheduleTime: scheduleTime.trim() || 'T7 20:00 & CN 20:00',
    targetName: targetName.trim() || 'Công Thành / Đẩy Trụ',
    sessions: DEFAULT_GUILD_SESSIONS.map((s) => ({ ...s })),
    members: [],
    minAttendanceRequired: 4,
    reportDate: new Date().toLocaleDateString('vi-VN'),
    createdAt: timestamp,
  };
}
